[package]
name = "webnes"
version = "0.1.0"
authors = ["Maté Antunovic <just.mate.antunovic@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
nes = {path = "../nes"}

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
